sudo: required
services:
- docker
language: bash
script:
- openssl aes-256-cbc -K $encrypted_81aa0260805a_key -iv $encrypted_81aa0260805a_iv -in .dmport.enc -out .dmport -d
- sudo apt-get -qq update
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo npm install -g @mumbacloud/dmport
- eval $(dmport --import "$(cat .dmport)")
- rm -f .dmport
- make
- ls -la
- cp app-release-unsigned.apk android_srt_examplerelease-unsigned_${TRAVIS_TAG}.apk
- cp app-debug.apk android_srt_example-debug_${TRAVIS_TAG}.apk
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push sofwerx/android_srt_example:${TRAVIS_TAG}
branches:
  only:
  - master
  - travis-only
  - "/^v\\d.*$/"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: "${GITHUB_TOKEN}"
  file:
  - android_srt_example-debug_${TRAVIS_TAG}.apk
  - android_srt_example-release-unsigned_${TRAVIS_TAG}.apk
  on:
    tags: true
    repo: "${TRAVIS_REPO_SLUG}"
